import 'dart:convert';

// Generated by https://quicktype.io

class Progreso {
  String pecho;
  String fecha;
  String peso;
  String espalda;
  String gluteos;
  String bicepDerecho;
  String bicepIzquierdo;
  String piernaIzquierda;
  String piernaDerecha;
  String cintura;
  String hombros;
  String correo;
}
